enableRadiation = true
enableChunkRads = true
enableMOTD = true
enableRadFogEffect = true
worldRadEffects = true
taintTrails = false
dropSingularity = true
dropCell = true
maxPlayerRad = 1000.0
radDecay = 0.01
radDamage = 0.05
radDamageThreshold = 200.0
radSickness = 200
radWater = 500
radConfusion = 700
radBlindness = 900
infoToastOffsetX = 15
infoToastOffsetY = 15
maxRad = 100000.0
radChunkDecay = 0.1
radChunkSpreadFactor = 0.2
radSpreadThreshold = 0.01
minRadDecayAmount = 0.01
radSourceInfluenceFactor = 0.1
radRandomizationFactor = 0.0
modelUpdateDistance = 3
modelStaticRenderDistance = 8
enableMissileNetworkTrack = true
missileTrackMaxRangeBlocks = 0
missileTrackInterval = 1
enableOcclusionCulling = false
instanceVboOrphanBeforeUpload = true
useInstancedStaticRendering = true
gpuBoneSkinning = true
useSlicedLight = false
useMultiDrawIndirect = true
mdiDebugLogDispatch = false
mdiVerboseSubdraws = false
maxInstancedInstancesPerPart = 4096
useColladaDoorAnimations = true
useColladaZUpConversion = true
vatsRenderDistanceChunks = 7
mk5TickTimeMs = 10
falloutRangePercent = 100
falloutDelay = 4
enableCraterBiomes = true
craterBiomeInnerChunkRad = 30.0
craterBiomeOuterChunkRad = 10.0
fatManRadius = 35
aSchrabRadius = 20
blastSpeed = 1024
limitExplosionLifespan = 0
thermalRenderMode = "FULL_SHADER"
enableDebugRender = true
debugRenderInSurvival = false
debugRenderTextSize = 0.2
debugRenderDistance = 4
enableDebugLogging = false

[radiationPixelEffect]
enableRadiationPixelEffect = true
radiationPixelEffectThreshold = 0.3
radiationPixelMaxIntensityRad = 100.0
radiationPixelEffectMaxDots = 250
radiationPixelEffectGreenChance = 0.5
radiationPixelMinLifetime = 5
radiationPixelMaxLifetime = 20

[obstructionHighlight]
enableObstructionHighlight = true
obstructionHighlightAlpha = 20
obstructionHighlightDuration = 2

[frackingTower]
maxPower = 5000000
consumption = 5000
solutionRequired = 10
delay = 20
oilPerDeposit = 1000
gasPerDepositMin = 100
gasPerDepositMax = 500
drainChance = 0.02
oilPerBedrockDeposit = 100
gasPerBedrockDepositMin = 10
gasPerBedrockDepositMax = 50
destructionRange = 75
